---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 25.03.19 0:00
---


local buffs = {"HpRegen","BodyArmor","Cloak","DieHard","Counter","GasesImmunity","Test","RPGbuff","ChopBuff","LowAttack","KillClone","SteelBodyBuff","SoulsDmgBuff","CounterblowsBuff","ExpShare","FastRunBuff","TonfsBuff"}

return buffs