---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 25.03.19 0:06
---
local RPD  = require "scripts/lib/commonClasses"
local RS = require "scripts/lib/Functions"
local buff = require "scripts/lib/buff"
local hero = RPD.Dungeon.hero
return buff.init{
    desc  = function ()
        return {
            icon          = 44,
            name          = "Подготовка",
            info          = "От тебя исходит аура света",
        }
    end,

charAct = function(self, buff)
local level = RPD.Dungeon.level

local x = level:cellX(buff.target:getPos())
        local y = level:cellY(buff.target:getPos())
    for i = x-2 , x + 2 do
           for j = y-2, y + 2 do
            local pos = level:cell(i,j)
            local enemy = RPD.Actor:findChar(pos) 
            local heroPos=RPD.Dungeon.hero:getPos()
            if pos == heroPos then
RS.spawnMob("DwemerBall",buff.target:getPos(),false)
            buff.target:die()
            end
         end
      end 
end


}
