---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 25.03.19 0:06
---
local RPD  = require "scripts/lib/commonClasses"
local buff = require "scripts/lib/buff"
local hero = RPD.Dungeon.hero

return buff.init{
    desc  = function ()
        return {
            icon          = 44,
            name          = "Исцеляющая аура",
            info          = "От тебя исходит аура света",
        }
    end,
    
    RPD.Sfx.CellEmitter:get(hero:getPos()):burst(RPD.Sfx.Speck:factory(RPD.Sfx.Speck.MAGIC ), 7);

charAct = function(hero, buff)
hero:damage(2,self)
end


}
